### ISSUE TITLE
what comes after the last \n should count as a line, even if empty (I think)

### ISSUE THREAD

**Issue by vassudanagunta** [vneenz/licofi#12]
Most *if not all* editors I've used behave as follows:
| text  | lines |
| ----- | ----- |
| ""    | 1     |
| "a"   | 1     |
| "\n"  | 2     |
| "a\nb | 2     |

In other words, a newline *creates a new line*, even if empty.

But if you, for example, provide `licofi` with `line 2` as input to the two line files in the table, you get an `Error: Column 1 does not exist on line 2`. Neither `{line: 2, column: 1}` or `{line: 2, column: 0}` work with the default configuration.

I can work around this pretty easily, but just pointing this out for your consideration. I'll PR a test case additions to document current behavior.

**Comment by vneenz** [comment]
Hmmm. In my eyes this is currently working as intented. Let's say we have a string `"\n\n"`. With your proposal calling `fromLineColumn({line: 3, column: 1})` should return 2. However that return value couldn't be used to index into the source string as it is out of bounds.

**Comment by vassudanagunta** [comment]
I see what you're saying.

I think it depends on the purpose of the library, the semantics of "line", and whether a file with `\n\n` is a two-line file or a three-line file, and whether indexes point characters or positions.

The existing behavior is correct if `\n\n` is a two line file or if indexes only point to **characters**.

But if `\n\n` is a three line file, and one is indexing **positions**, then either asking for the position of the caret if placed after the final character or asking for the offset of line 3 would be legitimate queries, I think. I am writing a parser, so that's why it makes sense to me. Same for someone writing an editor I think. 

But it's not a big deal. You're the boss 🙂.  If I continue to use licofi I'll just have to wrap it with the semantics I need.
